// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTaA4cf8TbXtxHM1clFdYcJNnnKaJvL8Y',
    appId: '1:878055321236:web:fea5cedc0942974d330e81',
    messagingSenderId: '878055321236',
    projectId: 'testappfirebase-f6c44',
    authDomain: 'testappfirebase-f6c44.firebaseapp.com',
    databaseURL: 'https://testappfirebase-f6c44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testappfirebase-f6c44.appspot.com',
    measurementId: 'G-RLXSLP9X3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsJVakE8d4dOEzO4xBemWDkTKmWmhGg9Y',
    appId: '1:878055321236:android:97f513f4bc5c1911330e81',
    messagingSenderId: '878055321236',
    projectId: 'testappfirebase-f6c44',
    databaseURL: 'https://testappfirebase-f6c44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testappfirebase-f6c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARHgXCd-GrZdMARqvZhia9hicppvge8tc',
    appId: '1:878055321236:ios:7105a2628d941fbc330e81',
    messagingSenderId: '878055321236',
    projectId: 'testappfirebase-f6c44',
    databaseURL: 'https://testappfirebase-f6c44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testappfirebase-f6c44.appspot.com',
    iosBundleId: 'com.example.testappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARHgXCd-GrZdMARqvZhia9hicppvge8tc',
    appId: '1:878055321236:ios:99b1615c77c3c13a330e81',
    messagingSenderId: '878055321236',
    projectId: 'testappfirebase-f6c44',
    databaseURL: 'https://testappfirebase-f6c44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testappfirebase-f6c44.appspot.com',
    iosBundleId: 'com.example.testappfirebase.RunnerTests',
  );
}
